dummy_data = {
    "column-names": [
        "lmk-key",
        "address1",
        "address2",
        "address3",
        "postcode",
        "building-reference-number",
        "current-energy-rating",
        "potential-energy-rating",
        "current-energy-efficiency",
        "potential-energy-efficiency",
        "property-type",
        "built-form",
        "inspection-date",
        "local-authority",
        "constituency",
        "county",
        "lodgement-date",
        "transaction-type",
        "environment-impact-current",
        "environment-impact-potential",
        "energy-consumption-current",
        "energy-consumption-potential",
        "co2-emissions-current",
        "co2-emiss-curr-per-floor-area",
        "co2-emissions-potential",
        "lighting-cost-current",
        "lighting-cost-potential",
        "heating-cost-current",
        "heating-cost-potential",
        "hot-water-cost-current",
        "hot-water-cost-potential",
        "total-floor-area",
        "energy-tariff",
        "mains-gas-flag",
        "floor-level",
        "flat-top-storey",
        "flat-storey-count",
        "main-heating-controls",
        "multi-glaze-proportion",
        "glazed-type",
        "glazed-area",
        "extension-count",
        "number-habitable-rooms",
        "number-heated-rooms",
        "low-energy-lighting",
        "number-open-fireplaces",
        "hotwater-description",
        "hot-water-energy-eff",
        "hot-water-env-eff",
        "floor-description",
        "floor-energy-eff",
        "floor-env-eff",
        "windows-description",
        "windows-energy-eff",
        "windows-env-eff",
        "walls-description",
        "walls-energy-eff",
        "walls-env-eff",
        "secondheat-description",
        "sheating-energy-eff",
        "sheating-env-eff",
        "roof-description",
        "roof-energy-eff",
        "roof-env-eff",
        "mainheat-description",
        "mainheat-energy-eff",
        "mainheat-env-eff",
        "mainheatcont-description",
        "mainheatc-energy-eff",
        "mainheatc-env-eff",
        "lighting-description",
        "lighting-energy-eff",
        "lighting-env-eff",
        "main-fuel",
        "wind-turbine-count",
        "heat-loss-corridor",
        "unheated-corridor-length",
        "floor-height",
        "photo-supply",
        "solar-water-heating-flag",
        "mechanical-ventilation",
        "address",
        "local-authority-label",
        "constituency-label",
        "posttown",
        "construction-age-band",
        "lodgement-datetime",
        "tenure",
        "fixed-lighting-outlets-count",
        "low-energy-fixed-light-count",
        "uprn",
        "uprn-source"
    ],
    "rows": [
        {
            "low-energy-fixed-light-count": "",
            "address": "30 Alexandra Road, Muswell Hill",
            "uprn-source": "Energy Assessor",
            "floor-height": "2.4",
            "heating-cost-potential": "494",
            "unheated-corridor-length": "",
            "hot-water-cost-potential": "71",
            "construction-age-band": "England and Wales: 1967-1975",
            "potential-energy-rating": "B",
            "mainheat-energy-eff": "Good",
            "windows-env-eff": "Good",
            "lighting-energy-eff": "Very Good",
            "environment-impact-potential": "79",
            "glazed-type": "double glazing installed during or after 2002",
            "heating-cost-current": "599",
            "address3": "",
            "mainheatcont-description": "Programmer, room thermostat and TRVs",
            "sheating-energy-eff": "N/A",
            "property-type": "House",
            "local-authority-label": "Barnet",
            "fixed-lighting-outlets-count": "9",
            "energy-tariff": "Single",
            "mechanical-ventilation": "natural",
            "hot-water-cost-current": "158",
            "county": "",
            "postcode": "N10 2RT",
            "solar-water-heating-flag": "N",
            "constituency": "E14000636",
            "co2-emissions-potential": "1.5",
            "number-heated-rooms": "3",
            "floor-description": "Solid, no insulation (assumed)",
            "energy-consumption-potential": "113",
            "local-authority": "E09000003",
            "built-form": "End-Terrace",
            "number-open-fireplaces": "0",
            "windows-description": "Fully double glazed",
            "glazed-area": "Normal",
            "inspection-date": "2022-04-01",
            "mains-gas-flag": "Y",
            "co2-emiss-curr-per-floor-area": "46",
            "address1": "30 Alexandra Road",
            "heat-loss-corridor": "",
            "flat-storey-count": "",
            "constituency-label": "Chipping Barnet",
            "roof-energy-eff": "Very Poor",
            "total-floor-area": "76.0",
            "building-reference-number": "10003180527",
            "environment-impact-current": "57",
            "co2-emissions-current": "3.5",
            "roof-description": "Flat, limited insulation (assumed)",
            "floor-energy-eff": "N/A",
            "number-habitable-rooms": "3",
            "address2": "Muswell Hill",
            "hot-water-env-eff": "Good",
            "posttown": "LONDON",
            "mainheatc-energy-eff": "Good",
            "main-fuel": "mains gas (not community)",
            "lighting-env-eff": "Very Good",
            "windows-energy-eff": "Good",
            "floor-env-eff": "N/A",
            "sheating-env-eff": "N/A",
            "lighting-description": "Low energy lighting in all fixed outlets",
            "roof-env-eff": "Very Poor",
            "walls-energy-eff": "Good",
            "photo-supply": "0.0",
            "lighting-cost-potential": "49",
            "mainheat-env-eff": "Good",
            "multi-glaze-proportion": "100",
            "main-heating-controls": "",
            "lodgement-datetime": "2022-08-25 12:07:54",
            "flat-top-storey": "",
            "current-energy-rating": "D",
            "secondheat-description": "None",
            "walls-env-eff": "Good",
            "transaction-type": "rental",
            "uprn": "200002791",
            "current-energy-efficiency": "63",
            "energy-consumption-current": "261",
            "mainheat-description": "Boiler and radiators, mains gas",
            "lighting-cost-current": "49",
            "lodgement-date": "2022-08-25",
            "extension-count": "0",
            "mainheatc-env-eff": "Good",
            "lmk-key": "a1c29898fb593f01ee6d0f50785950369d9ce1ccf1d417ea8cbe89d1bb73c499",
            "wind-turbine-count": "0",
            "tenure": "Rented (social)",
            "floor-level": "",
            "potential-energy-efficiency": "82",
            "hot-water-energy-eff": "Good",
            "low-energy-lighting": "100",
            "walls-description": "Cavity wall, filled cavity",
            "hotwater-description": "From main system"
        }
    ]
}